# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BATCH_INFO_JOBCONFIG',
            fields=[
                ('nn_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nn_wf_ver_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('period', models.IntegerField()),
                ('type', models.CharField(max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('last_updated_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NN_DEF_LIST_INFO',
            fields=[
                ('nn_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('biz_cate', models.CharField(max_length=10)),
                ('biz_sub_cate', models.CharField(max_length=10)),
                ('nn_title', models.CharField(max_length=100)),
                ('nn_desc', models.CharField(blank=True, default='', max_length=5000)),
                ('use_flag', models.CharField(blank=True, default='', max_length=1)),
                ('dir', models.CharField(blank=True, default='', max_length=200)),
                ('config', models.CharField(blank=True, default='', max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('last_updated_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NN_VER_BATCHLIST_INFO',
            fields=[
                ('nn_batch_ver_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nn_ver_wflist_info_nn_ver', models.CharField(max_length=50)),
                ('nn_batch_ver_info', models.CharField(blank=True, default='', max_length=50)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
                ('job_end_time', models.DateTimeField()),
                ('model_acc', models.IntegerField(default=0)),
                ('train_progress', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('last_updated_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NN_VER_WFLIST_INFO',
            fields=[
                ('nn_wf_ver_id', models.AutoField(primary_key=True, serialize=False)),
                ('nn_def_list_info_nn_id', models.CharField(blank=True, default='', max_length=50)),
                ('nn_wf_ver_info', models.CharField(max_length=100)),
                ('condition', models.CharField(blank=True, default='', max_length=50)),
                ('active_flag', models.CharField(blank=True, default='', max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('last_updated_by', models.IntegerField(default=0)),
                ('nn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.NN_DEF_LIST_INFO')),
            ],
        ),
        migrations.CreateModel(
            name='NN_WF_EASY_MODE_RULE',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('easy_mode_purp', models.CharField(max_length=2)),
                ('easy_mode_data_type', models.CharField(max_length=2)),
                ('easy_mode_store_type', models.CharField(max_length=2)),
                ('easy_mode_data_size', models.CharField(max_length=2)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('last_updated_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NN_WF_NODE_INFO',
            fields=[
                ('nn_wf_node_id', models.AutoField(primary_key=True, serialize=False)),
                ('nn_wf_node_name', models.CharField(max_length=50)),
                ('wf_node_status', models.IntegerField()),
                ('node_config_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('node_draw_x', models.IntegerField()),
                ('node_draw_y', models.IntegerField()),
                ('task_fin_flag', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('last_updated_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NN_WF_NODE_RELATION',
            fields=[
                ('nn_wf_relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('nn_wf_node_name_1', models.CharField(max_length=50)),
                ('nn_wf_node_name_2', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('last_updated_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NN_WF_STATE_INFO',
            fields=[
                ('wf_state_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nn_id', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('last_updated_by', models.IntegerField(default=0)),
                ('nn_wf_ver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.NN_VER_WFLIST_INFO')),
            ],
        ),
        migrations.CreateModel(
            name='TRAIN_SUMMARY_ACCLOSS_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nn_id', models.CharField(max_length=50)),
                ('nn_wf_ver_id', models.CharField(max_length=50)),
                ('acc_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('loss_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('last_updated_by', models.IntegerField(default=0)),
                ('nn_batch_ver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.NN_VER_BATCHLIST_INFO')),
            ],
        ),
        migrations.CreateModel(
            name='TRAIN_SUMMARY_RESULT_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nn_id', models.CharField(max_length=50)),
                ('nn_wf_ver_id', models.CharField(max_length=50)),
                ('result_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('last_updated_by', models.IntegerField(default=0)),
                ('nn_batch_ver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.NN_VER_BATCHLIST_INFO')),
            ],
        ),
        migrations.CreateModel(
            name='WF_TASK_MENU_RULE',
            fields=[
                ('wf_task_menu_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wf_task_menu_name', models.CharField(blank=True, max_length=50)),
                ('wf_task_menu_desc', models.CharField(blank=True, max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('last_updated_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WF_TASK_REALATION_RULE',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('wf_task_submenu_id_1', models.CharField(max_length=10)),
                ('wf_task_submenu_id_2', models.CharField(max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('last_updated_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WF_TASK_SUBMENU_RULE',
            fields=[
                ('wf_task_submenu_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wf_task_submenu_name', models.CharField(blank=True, max_length=100)),
                ('wf_task_submenu_desc', models.CharField(blank=True, max_length=200)),
                ('wf_node_class_name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('last_updated_by', models.IntegerField(default=0)),
                ('wf_task_menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.WF_TASK_MENU_RULE')),
            ],
        ),
        migrations.AddField(
            model_name='nn_wf_node_relation',
            name='wf_state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.NN_WF_STATE_INFO'),
        ),
        migrations.AddField(
            model_name='nn_wf_node_info',
            name='wf_state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.NN_WF_STATE_INFO'),
        ),
        migrations.AddField(
            model_name='nn_wf_node_info',
            name='wf_task_submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.WF_TASK_SUBMENU_RULE'),
        ),
        migrations.AddField(
            model_name='nn_wf_easy_mode_rule',
            name='wf_state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.NN_WF_STATE_INFO'),
        ),
        migrations.AddField(
            model_name='nn_ver_batchlist_info',
            name='nn_wf_ver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.NN_VER_WFLIST_INFO'),
        ),
        migrations.AddField(
            model_name='batch_info_jobconfig',
            name='nn_batch_ver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.NN_VER_BATCHLIST_INFO'),
        ),
    ]
