# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NN_DEF_LIST_INFO',
            fields=[
                ('nn_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('biz_cate', models.CharField(max_length=10)),
                ('biz_sub_cate', models.CharField(max_length=10)),
                ('nn_title', models.CharField(max_length=100)),
                ('nn_desc', models.CharField(blank=True, default='', max_length=5000)),
                ('use_flag', models.CharField(blank=True, default='', max_length=1)),
                ('dir', models.CharField(blank=True, default='', max_length=200)),
                ('config', models.CharField(blank=True, default='', max_length=1)),
                ('created_by', models.CharField(blank=True, default='', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(blank=True, default='', max_length=50)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NN_VER_WFLIST_INFO',
            fields=[
                ('nn_wf_ver_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nn_def_list_info_nn_id', models.CharField(blank=True, default='', max_length=50)),
                ('nn_wf_ver_info', models.CharField(max_length=100)),
                ('condition', models.CharField(blank=True, default='', max_length=50)),
                ('active_flag', models.CharField(blank=True, default='', max_length=1)),
                ('created_by', models.CharField(blank=True, default='', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(blank=True, default='', max_length=50)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('nn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.NN_DEF_LIST_INFO')),
            ],
        ),
    ]
