from django.db import models
from django.utils.translation import ugettext as _

# Create your models here.
class LOG_INFO(models.Model):

    attr1 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr2 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr3 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr4 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr5 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr6 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr7 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr8 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr9 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr10 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr11 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr12 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr13 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr14 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr15 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr16 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr17 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr18 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr19 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr20 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr21 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr22 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr23 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr24 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr25 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr26 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr27 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr28 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr29 = models.CharField(max_length=50000, blank=True, default='', null=True)
    attr30 = models.CharField(max_length=50000, blank=True, default='', null=True)
    log_id = models.IntegerField(default=0, null=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    last_update_date = models.DateTimeField(auto_now_add=True)
    created_by = models.IntegerField(default=0)
    last_updated_by = models.IntegerField(default=0)
